// Import the required libraries
import java.util.*;


public class Guessing_the_number_from_range
{
    // function To generate random number between the given range
    public static int getRandomNumber(int min, int max) 
    {
    Random random = new Random();
    return random.nextInt(max - min) + min;
    }
  public static void main(String[] args) 
  {
    // Explaination of the game
    System.out.println("----------------Welcome to the game of Guessing The Number----------------");
    System.out.println();
    System.out.println("Hello Gamer");
    System.out.println("Today you will learn and play the guessing number game ,this game will be fun");
    System.out.println();
    System.out.println();
    System.out.println("The game is very simple::");
    System.out.println();
    System.out.println("------------Now I will like to explain the Rules/Condition of the game------------");
    System.out.println();
    System.out.println("1.Enter any two random numbers as you wish\n");
    System.out.println("2.You have to enter two numbers with at least gap of 15 between them\n");
    System.out.println("3.The Computer will generate any number that is between the numbers you have entered\n ");
    System.out.println("4.You have to guess the number which computer has Generated randomly\n");
    System.out.println("5.you have 5 chance to guess the correct number\n");
    System.out.println("6.If you Guessed the correct number in 5 round you Win or else you will Lose\n");
    System.out.println("7.If you Guessed the correct Number in any rounds then your score will be given as shown below\n");
    System.out.println("  1st round-     score=100");
    System.out.println("  2nd round-     score=80");
    System.out.println("  3rd round-     score=60");
    System.out.println("  4th round-     score=30");
    System.out.println("  5th round-     score=10");
    System.out.println("  else     -     score=0\n");
    System.out.println("8.I will also help you for guessing the number.");
    System.out.println("9.I will let you know whether the number you have guessed \n is smaller or greater than number generated by computer");
     boolean understood=false;
     System.out.println();
     System.out.print("Enter 1 if you have understood the rules else enter 0 ::");
     Scanner sc=new Scanner(System.in);
     int guess=sc.nextInt();
     if(guess==0)
     {
         // explaination of game with an example
        System.out.println();
        System.out.println("Don't take tension I will give you an example so you can understand game easily"); 
        System.out.println("lets take an exmple if you entered 1 and 20 as two random numbers");
        System.out.println("Computer takes random number between 1 t0 20 e.g comp selected 10");
        System.out.println("Now you have 5 chances to predict this number ");
        System.out.println("Now let's play the game!--------");
        System.out.println();
     }
      


   System.out.println();
    // Tajking input from the gamer
   System.out.println("Enter the two numbers to let computer generate random number between them");
   System.out.print("Enter the first_no  ::");
   int first_no=sc.nextInt();
   System.out.println();
   System.out.print("Enter the second_no ::");
   int second_no=sc.nextInt();
   System.out.println();
   int random=getRandomNumber(first_no,second_no);
   if((first_no-second_no<15 && first_no-second_no>0) || (second_no-first_no<15 && second_no-first_no>0))
   {
      System.out.println("Please enter numbers with the minimum difference of 15 between them");
      System.out.println("Now Restart the game :: ");
      return;
   }

   System.out.println();
   int round=1;
   int score=0;
   while(round!=6)
   {
     // Checking if guessed number is correct or not
    System.out.println();
    System.out.print("Guess the number between ( "+Math.min(first_no,second_no)+"-"+Math.max(first_no,second_no)+" )  ::");
    int guessed_number=sc.nextInt();
    if(guessed_number==random)
    {
      System.out.println("HURRAY! You have 'WON' the game");
      System.out.println("You have Successfully guessed the number");
      if(round==1)
      {
       score=100;
      }
      else if(round==2)
      {
        score=80;
      }
      else if(round==3)
      {
        score=60;
      }
      else if(round==4)
      {
        score=30;
      }
      else{
        score=10;
      }
      // System.out.println("Thank you for playing the game");
      break;
    }
    else{
      System.out.println("The number guessed is incoreect");
      System.out.println();
      if((5-round==0))
      {
        System.out.println("You have finished all your rounds");
        System.out.println("You failed to Guess the number");
        break;
      }
      else if(guessed_number>random)
      {
        System.out.println("I will provide some help now champ::");
        System.out.println("The number you have enterd is ::'bigeer':: than number generated by computer");
        System.out.println("Try in next round by entering number ::'smaller':: than Guessed number");
        System.out.println("you still have::"+(5-round)+" round left");
        System.out.println("Best of luck for further rounds");
      }
      else if(guessed_number<random)
      {
        System.out.println("The number you have enterd is ::'smaller':: than  number genrated by a Computer");
        System.out.println("Try in next round by entering number ::'larger'::  than Guessed number");
        System.out.println("you still have::"+(5-round)+" round left");
        System.out.println("best of luck for further rounds");
      }
      else
      {
        System.out.println("You have entered number out of the range given by you");
        if(first_no>second_no)
        System.out.println("please enter numbers between the range ( "+first_no+"-"+second_no+" )");
        else
        System.out.println("please enter numbers between the range ( "+second_no+"-"+first_no+" )");
      }
    }


    round++;
   }
   if(score==0)
   {
    System.out.println();
    System.out.println("OOPS! You 'LOST' the game");
    System.out.println("Looks like your luck is not on your side");
    System.out.println();
    System.out.println("No problem champ! you can always try next time");
   }
   System.out.println();
   System.out.println("Your final score is:: ("+score+")");
   System.out.println();
   System.out.println("-----------------Thank you for playing the game----------------------");

  }
}
